package com.backend.boardMate.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.util.List;

@Entity
@Data
public class Property {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    private String location;
    private Double latitude;
    private Double longitude;
    private String mapLink;
    private Double price;
    private String type;
    private Integer bedrooms;
    private Integer bathrooms;
    private Integer rooms;
    private Double area;
    private String description;

    @ElementCollection
    private List<String> amenities;

//    private String imageUrl;

    @ElementCollection
    private List<String> imageUrls; // Store URLs of uploaded images
//
//     Getters and setters (generated by Lombok)
}
